CREATE TABLE associates (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    designation VARCHAR(255) NOT NULL,
    create_at DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

